# Generated by Django 3.0.8 on 2020-09-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='Name of the sender', max_length=200)),
                ('lasttname', models.CharField(help_text='Last Name of the sender', max_length=200)),
                ('areacode', models.CharField(help_text='Last Name of the sender', max_length=200)),
                ('telnum', models.CharField(help_text='Last Name of the sender', max_length=200)),
                ('emailid', models.EmailField(max_length=200)),
                ('feedback', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
